### ISSUE TITLE
Refactor _.reduce to correctly implement missing seed

### ISSUE THREAD

**Issue by gregthompson27** [gagecantrelle/underpants#1]
https://github.com/gagecantrelle/underpants/blob/186d88d096e3510c99d58b576e180259e4de969c/underpants.js#L591-L604

@gagecantrelle, your reduce function is off a bit. You can see what I mean if you check out [this JS bin](https://jsbin.com/peweluhuru/2/edit?js,console) that I made and plugged your reduce function into.

We do want to check if there is no seed, which you are doing on line 593, but the seed being `0` or not really should have no bearing on the rest of the function.

The logic that you're missing is that if there is no seed, in addition to setting the seed to be the first value of the array (which you are doing), we want to start our loop at the second value of the array instead of the first value. How can we implement this with code?

**Comment by gregthompson27** [comment]
@gregthompson27 hey Mr. Greg, I made project revisions

**Comment by gagecantrelle** [comment]
@gregthompson27 : hey I made the changes
